[package]
name = "echo"
version = "0.1.0"
edition = "2021"
authors = ["Jorge Mayoral Álvarez <contact@yorch.dev>"]
description = "Rust echo"

[dependencies]
clap = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
